version: '3.8'

services:
  classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classifier_service
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
